### ISSUE TITLE
Can not open an user account settings from the administration panel

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#18]

**Comment by devbhuwan** [comment]
After debugging JS files I found, following error: 
![1](https://cloud.githubusercontent.com/assets/12765300/19828384/17e280c8-9dcd-11e6-9db1-1684bcbadabb.PNG)

Actually, this is because in Web Client Module:
   /static/common/module.js line 176 : scope.$on(platformParameters.events.SIDEBAR_ELEMENT_SELECTED ...

Type variable SIDEBAR_ELEMENT_SELECTED not found inside this file or platformParameters having js file not include in html.

**Comment by cykeromens** [comment]
@devbhuwan  how do i replicate this problem?

**Comment by mariuszkumor** [comment]
In the admin panel click on the user's avatar icon, and then the dashboard position.

**Comment by mariuszkumor** [comment]
Functionality has been removed. Only from the application site is available.
