### ISSUE TITLE
Building issue: - install -DskipDocker not working

### ISSUE THREAD

**Issue by yogeshmprajapati** [abixen/abixen-platform#214]
Hi Team ,
I tried to run maven install 

> [install -DskipDocker]

 and getting below error:

> [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (default) on project abixen-platform-core: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect -> [Help 1]

Seems like it is ignoring **-DskipDocker** and trying to connect docker on port **2375**.
Let me know if i missed anything.

![1111](https://cloud.githubusercontent.com/assets/14257174/21307502/c2531fd0-c5fb-11e6-9a5b-298c1290276a.png)

**Comment by mariuszkumor** [comment]
What of you run from command line: **mvn install -DskipDocker** ?

**Comment by yogeshmprajapati** [comment]
Yes, i have added image in question, you can check it.

**Comment by mariuszkumor** [comment]
I saw it, but please run it from command line, not from IDEA.

**Comment by YogenRaii** [comment]
From IDEA also, it should work. I get this error when i have not started
redis server. In logs you got, you can see that it is not being able to
connect to 127.0.0.1:####

On Mon, Dec 19, 2016 at 4:33 AM Mariusz Kumor <notifications@github.com>
wrote:

I saw it, but please run it from command line, not from IDEA.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/abixen/abixen-platform/issues/214#issuecomment-267920049>,
or mute the thread

**Comment by mariuszkumor** [comment]
This issue indicates docker, not redis.
